# Generated by Django 4.2.3 on 2023-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='stock_qty',
            field=models.IntegerField(blank=True),
        ),
    ]
