# Generated by Django 4.2.3 on 2023-09-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productline_stock_qty_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
    ]
