# Generated by Django 4.2.3 on 2023-09-22 21:52

from django.db import migrations
import product.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='order',
            field=product.fields.OrderField(blank=True, default=0),
        ),
    ]
